### PR TITLE
Remove unused dependency and remove extraneous files

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
This will hopefully fix the following warning I get on Windows:

```
ClobberWarning: This transaction has incompatible packages due to a shared path.
557  packages: conda-forge/win-64::python-3.8.5-h5fd99cc_2_cpython, conda-forge/win-64::librsvg-2.49.4-h4f1b82b_0
558  path: 'scripts/2to3-script.py'
559ClobberWarning: This transaction has incompatible packages due to a shared path.
560  packages: conda-forge/win-64::python-3.8.5-h5fd99cc_2_cpython, conda-forge/win-64::librsvg-2.49.4-h4f1b82b_0
561  path: 'scripts/2to3.exe'
562ClobberWarning: This transaction has incompatible packages due to a shared path.
563  packages: conda-forge/win-64::python-3.8.5-h5fd99cc_2_cpython, conda-forge/win-64::librsvg-2.49.4-h4f1b82b_0
564  path: 'scripts/idle-script.py'
565ClobberWarning: This transaction has incompatible packages due to a shared path.
566  packages: conda-forge/win-64::python-3.8.5-h5fd99cc_2_cpython, conda-forge/win-64::librsvg-2.49.4-h4f1b82b_0
567  path: 'scripts/idle.exe'
568ClobberWarning: This transaction has incompatible packages due to a shared path.
569  packages: conda-forge/win-64::python-3.8.5-h5fd99cc_2_cpython, conda-forge/win-64::librsvg-2.49.4-h4f1b82b_0
570  path: 'scripts/pydoc-script.py'
571ClobberWarning: This transaction has incompatible packages due to a shared path.
572  packages: conda-forge/win-64::python-3.8.5-h5fd99cc_2_cpython, conda-forge/win-64::librsvg-2.49.4-h4f1b82b_0
573  path: 'scripts/pydoc.exe'
574done
575Executing transaction: ...working... 
576ClobberWarning: Conda was asked to clobber an existing path.
577  source path: C:\Miniconda\pkgs\librsvg-2.49.4-h4f1b82b_0\Scripts\2to3-script.py
578  target path: C:\Miniconda\conda-bld\rfi-file-monitor-extensions_1598530311704\_test_env\Scripts\2to3-script.py
579ClobberWarning: Conda was asked to clobber an existing path.
580  source path: C:\Miniconda\pkgs\librsvg-2.49.4-h4f1b82b_0\Scripts\2to3.exe
581  target path: C:\Miniconda\conda-bld\rfi-file-monitor-extensions_1598530311704\_test_env\Scripts\2to3.exe
582ClobberWarning: Conda was asked to clobber an existing path.
583  source path: C:\Miniconda\pkgs\librsvg-2.49.4-h4f1b82b_0\Scripts\idle-script.py
584  target path: C:\Miniconda\conda-bld\rfi-file-monitor-extensions_1598530311704\_test_env\Scripts\idle-script.py
585ClobberWarning: Conda was asked to clobber an existing path.
586  source path: C:\Miniconda\pkgs\librsvg-2.49.4-h4f1b82b_0\Scripts\idle.exe
587  target path: C:\Miniconda\conda-bld\rfi-file-monitor-extensions_1598530311704\_test_env\Scripts\idle.exe
588ClobberWarning: Conda was asked to clobber an existing path.
589  source path: C:\Miniconda\pkgs\librsvg-2.49.4-h4f1b82b_0\Scripts\pydoc-script.py
590  target path: C:\Miniconda\conda-bld\rfi-file-monitor-extensions_1598530311704\_test_env\Scripts\pydoc-script.py
591ClobberWarning: Conda was asked to clobber an existing path.
592  source path: C:\Miniconda\pkgs\librsvg-2.49.4-h4f1b82b_0\Scripts\pydoc.exe
593  target path: C:\Miniconda\conda-bld\rfi-file-monitor-extensions_1598530311704\_test_env\Scripts\pydoc.exe
```

**Comment by jenzopr** [comment]
Yep, that should have fixed it. I will review once the checks are done.

**Comment by pkgw** [comment]
The `exe` related items are/were due to a buggy Windows Python package — see discussion in conda-forge/python-feedstock#384. We have marked the offending packages as broken, so it shouldn't be necessary to edit the `bld.bat` here. (And based on my investigations, doing so wouldn't have helped with the broken packages, since the problematic files seemed to be created after the build process finished.)

Travis failure looks transient — [404 downloading the source package](https://travis-ci.com/github/conda-forge/librsvg-feedstock/builds/181641623#L608).

**Comment by tschoonj** [comment]
Thanks @pkgw for the clarification: one thing I don't understand is why these packages that have been marked as broken are still being downloaded...

I will remove the `del` statements from `bld.bat`.

**Comment by tschoonj** [comment]
I am going to get rid of that Travis build and switch it to azure

**Comment by pkgw** [comment]
@tschoonj I may have been unclear: the problematic *Python* package have been marked as broken (conda-forge/admin-requests#116, conda-forge/admin-requests#117), but we haven't tracked down packages like `librsvg` and `tectonic` that are bad because they were *built with* the bad Python. In principle it should be possible to do so, but it would take some legwork and I haven't seen any evidence that anyone is working on that.

**Comment by tschoonj** [comment]
@pkgw is there anything else that I need to do in this PR?

**Review by pkgw — APPROVED** [review]
LGTM

**Comment by pkgw** [comment]
@tschoonj Nope, I just lost track of this one.

**Pull request merged**
